# Generated by Django 5.1 on 2024-08-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_inventario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
