# Generated by Django 5.0.6 on 2024-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_inventario_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_active',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Agotado')], default=1),
        ),
    ]
