# Generated by Django 5.0.6 on 2024-08-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_rename_is_active_userprofile_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='estado',
            new_name='is_active',
        ),
    ]
