# Generated by Django 5.0.6 on 2024-08-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_rename_estado_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[('Desactivado', 'Desactivado'), ('Activo', 'Activo')], default=2),
        ),
    ]
