# Generated by Django 5.0.6 on 2024-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Desactivado'), (2, 'Activado')], default=2),
        ),
    ]
