# Generated by Django 5.0.6 on 2024-08-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_userprofile_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='username',
            new_name='nombre',
        ),
    ]
