# Generated by Django 5.0.6 on 2024-08-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_rename_email_userprofile_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='estado',
        ),
    ]
