# Generated by Django 5.0.6 on 2024-08-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_remove_userprofile_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='numero',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='numero',
            new_name='documento',
        ),
    ]
