# Generated by Django 5.0.6 on 2024-08-23 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_rename_numero_userprofile_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='documento',
            field=models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='El número de documento debe tener al menos 8 dígitos y maximo 10 dígitos.')]),
        ),
    ]
