# Generated by Django 5.0.6 on 2024-08-23 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_alter_userprofile_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='documento',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(8, message='El número de documento debe tener al menos 8 caracteres.'), django.core.validators.MaxLengthValidator(10, message='El número de documento debe tener como máximo 10 caracteres.')]),
        ),
    ]
