# Generated by Django 5.0.6 on 2024-08-23 11:07

import inicio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_alter_userprofile_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='documento',
            field=models.IntegerField(unique=True, validators=[inicio.models.validate_document_length]),
        ),
    ]
