# Generated by Django 5.0.6 on 2024-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_alter_userprofile_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(choices=[('protesis', 'Prótesis'), ('ortodoncia', 'Ortodoncia')], default='protesis', max_length=20),
        ),
    ]
