# Generated by Django 5.0.6 on 2024-09-11 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_alter_cita_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fecha',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
