# Generated by Django 5.0.6 on 2024-09-18 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_alter_fecha_final_alter_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
