# Generated by Django 5.0.6 on 2024-09-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0022_alter_fecha_fecha_hora'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fecha',
            unique_together={('fecha', 'hora')},
        ),
        migrations.RemoveField(
            model_name='fecha',
            name='final',
        ),
        migrations.RemoveField(
            model_name='fecha',
            name='inicio',
        ),
    ]
