# Generated by Django 5.0.6 on 2024-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0023_alter_fecha_unique_together_remove_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Asistida', 'Asistida'), ('Cancelada', 'Cancelada'), ('inasistida', 'No Asistió')], default='programada', max_length=20),
        ),
    ]
