# Generated by Django 5.0.6 on 2024-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0024_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Asistida', 'Asistida'), ('Cancelada', 'Cancelada'), ('inasistida', 'No Asistió')], default='Programada', max_length=20),
        ),
    ]
